# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Movies Database' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, '10.0'
  # Pods for Movies Database
  pod 'CodableAlamofire'
  pod 'AlamofireImage'
  pod 'JGProgressHUD'
  pod 'XCDYouTubeKit', '~> 2.7'
  
end
